[server]
addr = "0.0.0.0:20160"
advertise-addr = "172.16.0.101:20160"
status-addr = "0.0.0.0:20180"
advertise-status-addr = "172.16.0.101:20180"
labels = { host = "vm1" }

[storage]
data-dir = "/data/tikv"

[raftstore]
raftdb-path = "/data/tikv/raft"

[rocksdb]
wal-dir = "/data/tikv/wal"

[rocksdb.titan]
enabled = false

[rocksdb.defaultcf]
block-size = "64KB"
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]
target-file-size-base = "256MB"

[rocksdb.writecf]
block-size = "64KB"
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

[rocksdb.lockcf]
block-size = "64KB"
compression-per-level = ["no", "no", "no", "no", "no", "no", "no"]

[raftdb.defaultcf]
compression-per-level = ["no", "no", "lz4", "lz4", "lz4", "zstd", "zstd"]

[coprocessor]

[pd]
endpoints = ["172.16.0.101:2379", "172.16.0.102:2379", "172.16.0.103:2379"]

[log]
level = "info"

[log.file]
filename = "/var/log/tikv/tikv.log"
